

const ACTIONS = {
    CATEGORIE_FILTER_ESTABELECIMENTO:{
        GET_ALL: 'CATEGORIE_FILTER_ESTABELECIMENTO/GET_ALL',
        ADD_ITEM_SELECTED:'CATEGORIE_FILTER_ESTABELECIMENTO/ADD_ITEM_SELECTED',
        APPLY_FILTER_SELECTED:'CATEGORIE_FILTER_ESTABELECIMENTO/APPLY_FILTER_SELECTED',
        CLEAR_FILTER: 'CATEGORIE_FILTER_ESTABELECIMENTO/CLEAR_FILTER'
    },
    ESTABELECIMENTO_SEARCH:{
        REQUEST: 'ESTABELECIMENTO_SEARCH/REQUEST',
        LIST_ITENS: 'ESTABELECIMENTO_SEARCH/LIST_ITENS',
        LOADING:'ESTABELECIMENTO_SEARCH/LOADING',
        RESET_PAGE:'ESTABELECIMENTO_SEARCH/RESET_PAGE',
        CHANGE_PAGE:'ESTABELECIMENTO_SEARCH/CHANGE_PAGE',
        RESET_PAGE_AND_DATA:'ESTABELECIMENTO_SEARCH/RESET_PAGE_AND_DATA',
        CHANGE_QUERY:'ESTABELECIMENTO_SEARCH/CHANGE_QUERY',
        CHANGE_PAGE_QUERY:'ESTABELECIMENTO_SEARCH/CHANGE_PAGE_QUERY',
        PESQUISAR:'ESTABELECIMENTO_SEARCH/PESQUISAR'

    }
}


export { ACTIONS }